pipeline {
    agent any
    
    parameters{
        string(defaultValue: "TEST", description: "some text description", name: "var_env" )
    }

    stages{
        stage("Demo"){
            steps{
                echo "string is is : ${params.var_env}"
            }
        }
    }

}